# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Eden Project 
email: admin@eden-project.com
description: > # this means to ignore newlines until "baseurl:"
    A warrior support foundation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eden-project.com" # the base hostname & protocol for your site
twitter_username: The_EdenProject
github_username:  bbriggs

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
